name: Github-Auto-Follow-Unfollow-View-User-List

on:
  workflow_dispatch:
  schedule:
    - cron: '50 7 * * 1-5'
permissions:
  contents: read
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Github-Auto-Follow-Unfollow-View-User-List
        uses: Huniko519/Github-Auto-Follow-Unfollow-View-User-List@main
        with:
          token: ${{ secrets.GH_PAT }}
          repository: ${{ github.prjctimg }}
          isReadmeUpdate: true
          safeUserList: 'Liu-Yong-HK,Huniko-Team'
