name: Update README

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update:
    uses: prjctimg/profile/.github/workflows/update.yml@main
    with:
      script-output: "direct"
      commit-message: "updated rss feed"
      git-user-name: "prjctimg"
      git-user-email: "prjctimg@outlook.com"
    secrets: inherit
